version: '3.8'
services:
  users:
    container_name: products
    build: ./products
    volumes: 
      -  ./products/code:/usr/src/app
    networks: 
      -  products
    ports: 
      -  "3001:3001"
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"
networks:
  products:
    driver: bridge
